name: Deploy to EC2

on:
  push:
    branches:
      - main   # jis branch se deploy karna hai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy files to EC2
        run: |
          rsync -avz --delete \
          --exclude='.git*' \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/mypropertysnagging/
